name: Continious Integration

on: [pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run black
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install black
        run: pip install black
      - name: run black
        run: black --line-length 89 --check .

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: install tox
        run: pip install tox
      - name: Tox
        run: tox -e py
